cc_test(
    name = "circular_buffer_test",
    size = "small",
    srcs = ["circular_buffer_test.cc"],
    deps = [
        "@boost//:circular_buffer",
        "@boost//:test",
    ],
)

cc_test(
    name = "test",
    srcs = ["test.cc"],
    deps = [
        "@boost//:test",
    ],
)

cc_test(
    name = "thread_test",
    size = "small",
    srcs = ["thread_test.cc"],
    deps = [
        "@boost//:test",
        "@boost//:thread",
    ],
)
