cc_test(
    name = "any_test",
    size = "small",
    srcs = ["any_test.cc"],
    deps = [
        "@boost//:any",
    ],
)

cc_test(
    name = "array_test",
    size = "small",
    srcs = ["array_test.cc"],
    deps = [
        "@boost//:array",
    ],
)

cc_test(
    name = "asio_test",
    size = "small",
    srcs = ["asio_test.cc"],
    deps = [
        "@boost//:asio",
        "@boost//:date_time",
    ],
)

cc_test(
    name = "assign_test",
    size = "small",
    srcs = ["assign_test.cc"],
    deps = [
        "@boost//:assign",
    ],
)

cc_test(
    name = "beast_test",
    size = "small",
    srcs = ["beast_test.cc"],
    deps = [
        "@boost//:beast",
    ],
)

cc_test(
    name = "bimap_test",
    size = "small",
    srcs = ["bimap_test.cc"],
    deps = [
        "@boost//:bimap",
    ],
)

cc_test(
    name = "bind_test",
    size = "small",
    srcs = ["bind_test.cc"],
    deps = [
        "@boost//:bind",
    ],
)

cc_test(
    name = "callable_traits_test",
    size = "small",
    srcs = ["callable_traits_test.cc"],
    deps = [
        "@boost//:callable_traits",
    ],
)

cc_test(
    name = "circular_buffer_test",
    size = "small",
    srcs = ["circular_buffer_test.cc"],
    deps = [
        "@boost//:circular_buffer",
    ],
)

cc_test(
    name = "context_test",
    size = "small",
    srcs = ["context_test.cc"],
    deps = [
        "@boost//:context",
    ],
)

cc_test(
    name = "compute_test",
    size = "small",
    srcs = ["compute_test.cc"],
    deps = [
        "@boost//:compute",
    ]
)

cc_test(
    name = "coroutine_test",
    size = "small",
    srcs = ["coroutine_test.cc"],
    deps = [
        "@boost//:coroutine",
    ]
)

cc_test(
    name = "dynamic_bitset_test",
    size = "small",
    srcs = ["dynamic_bitset_test.cc"],
    deps = [
        "@boost//:dynamic_bitset",
    ],
)

cc_test(
    name = "endian",
    size = "small",
    srcs = [ "endian.cc" ],
    deps = [
        "@boost//:endian",
        "@boost//:static_assert",
    ],
)

cc_test(
    name = "fiber_test",
    size = "small",
    srcs = ["fiber_test.cc"],
    deps = [
        "@boost//:fiber",
    ],
)

cc_test(
    name = "foreach_test",
    size = "small",
    srcs = ["foreach_test.cc"],
    deps = [
        "@boost//:foreach",
    ],
)

cc_test(
    name = "format_test",
    size = "small",
    srcs = ["format_test.cc"],
    copts = ["-Wno-unused-value"],
    deps = [
        "@boost//:format",
    ],
)

cc_test(
    name = "fusion_test",
    size = "small",
    srcs = ["fusion_test.cc"],
    deps = [
        "@boost//:fusion",
    ],
)

cc_test(
    name = "icl_test",
    size = "small",
    srcs = ["icl_test.cc"],
    deps = [
        "@boost//:icl",
    ],
)

cc_test(
    name = "iostreams_test",
    size = "small",
    srcs = ["iostreams_test.cc"],
    deps = [
        "@boost//:iostreams",
    ],
)

cc_test(
    name = "mp11_test",
    size = "small",
    srcs = ["mp11_test.cc"],
    deps = [
        "@boost//:mp11",
    ],
)

cc_test(
    name = "multiprecision_test",
    size = "small",
    srcs = ["multiprecision_test.cc"],
    deps = [
        "@boost//:multiprecision",
    ],
)

cc_test(
    name = "numeric_conversion_test",
    size = "small",
    srcs = ["numeric_conversion_test.cc"],
    deps = [
        "@boost//:numeric_conversion",
    ],
)

cc_test(
    name = "optional_test",
    size = "small",
    srcs = ["optional_test.cc"],
    deps = [
        "@boost//:optional",
    ],
)

cc_test(
    name = "process_test",
    size = "small",
    srcs = ["process_test.cc"],
    deps = [
        "@boost//:process",
    ],
)

cc_test(
    name = "program_options_test",
    size = "small",
    srcs = ["program_options_test.cc"],
    deps = [
        "@boost//:program_options",
    ],
)

cc_test(
    name = "ptr_container_test",
    size = "small",
    srcs = ["ptr_container_test.cc"],
    deps = [
        "@boost//:ptr_container",
    ],
)

cc_test(
    name = "random_test",
    size = "small",
    srcs = ["random_test.cc"],
    deps = [
        "@boost//:random",
    ],
)

cc_test(
    name = "rational_test",
    size = "small",
    srcs = ["rational_test.cc"],
    deps = [
        "@boost//:rational",
    ],
)

cc_test(
    name = "scope_exit_test",
    size = "small",
    srcs = ["scope_exit_test.cc"],
    deps = [
        "@boost//:scope_exit",
    ],
)

cc_test(
    name = "signals2_test",
    size = "small",
    srcs = ["signals2_test.cc"],
    deps = [
        "@boost//:signals2",
    ],
)

cc_test(
    name = "test",
    srcs = ["test.cc"],
    deps = [
        "@boost//:test",
    ],
)

cc_test(
    name = "thread_test",
    size = "small",
    srcs = ["thread_test.cc"],
    deps = [
        "@boost//:thread",
    ],
)

cc_test(
    name = "tokenizer_test",
    size = "small",
    srcs = ["tokenizer_test.cc"],
    deps = [
        "@boost//:tokenizer",
    ],
)

cc_test(
    name = "tribool_test",
    size = "small",
    srcs = ["tribool_test.cc"],
    deps = [
        "@boost//:tribool",
    ],
)

cc_test(
    name = "unordered_test",
    size = "small",
    srcs = ["unordered_test.cc"],
    deps = [
        "@boost//:unordered",
    ],
)

cc_test(
    name = "uuid_test",
    size = "small",
    srcs = ["uuid_test.cc"],
    deps = [
        "@boost//:uuid",
    ],
)

cc_test(
    name = "property_tree_test",
    size = "small",
    srcs = ["property_tree_test.cc"],
    deps = [
        "@boost//:property_tree",
    ],
)
